### ISSUE TITLE
Provide linux musl build

### ISSUE THREAD

**Issue by kahgeh** [kahgeh/open-sse#3]
Likely configuration in `release.yml`
```
  upload-linux-musl-assets:
    if: github.repository_owner == 'kahgeh'
    needs:
      - create-release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/github-actions/install-rust@main
        with:
          toolchain: stable
      - id: setup_open_ssl_on_musl
        run: |
          ln -s /usr/include/x86_64-linux-gnu/asm /usr/include/x86_64-linux-musl/asm 
          ln -s /usr/include/asm-generic /usr/include/x86_64-linux-musl/asm-generic
          ln -s /usr/include/linux /usr/include/x86_64-linux-musl/linux
          mkdir /musl
          wget https://github.com/openssl/openssl/archive/OpenSSL_1_1_1f.tar.gz
          tar zxvf OpenSSL_1_1_1f.tar.gz 
          cd openssl-OpenSSL_1_1_1f/
          CC="musl-gcc -fPIE -pie" ./Configure no-shared no-async --prefix=/musl --openssldir=/musl/ssl linux-x86_64
          make depend
          make -j$(nproc)
          make install
        env:
          PKG_CONFIG_ALLOW_CROSS: 1
          OPENSSL_STATIC: true
          OPENSSL_DIR: /musl
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: open-sse-server
          target: x86_64-unknown-linux-musl
          tar: all
      - uses: taiki-e/upload-rust-binary-action@v1          
        with:
          bin: open-sse-broker
          target: x86_64-unknown-linux-musl
          tar: all
          zip: windows          
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CARGO_PROFILE_RELEASE_LTO: true         
 ```
